### PR TITLE
Add Spanish Red Cross

### PR DESCRIPTION
**Pull request by yanokwa**

### CODE REVIEW

**Comment by danbjoseph** [comment]
should the link note that the destination video is in Spanish? or the user will find out if they click through?

**Comment by yanokwa** [comment]
I think it's a pleasant surprise! Also the visuals are pretty compelling to an English speaker.

**Comment by danbjoseph** [comment]
what's the order of the list?

**Comment by yanokwa** [comment]
Ordering is mostly by impact/size because my assumption is that people won't read everything.
Very open to some other ordering. Or maybe a map?

**Pull request merged**
